# Generated by Django 4.2.7 on 2023-11-16 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genotip', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewBorn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Düzenleme Tarihi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('numericalPainScale', models.PositiveSmallIntegerField(choices=[(0, '0. Ağrı Yok'), (1, '1.'), (2, '2.'), (3, '3.'), (4, '4.'), (5, '5. Orta Şiddetli Ağrı'), (6, '6.'), (7, '7.'), (8, '8.'), (9, '9.'), (10, '10. Şiddetli Ağrı')], default=0, verbose_name='Numerik Ağrı Skalası (0-10)')),
                ('wongBakerFacesPainScale', models.PositiveSmallIntegerField(choices=[(0, '0. Ağrı Yok'), (2, '2.'), (4, '4. Orta Şiddetli Ağrı'), (6, '6. Orta Şiddetli Ağrı'), (8, '8.'), (10, '10. Şiddetli Ağrı')], default=0, verbose_name='Yüz Skalası (0-10)')),
                ('behavioralFaceExpressionPainScale', models.PositiveSmallIntegerField(choices=[(0, '0. Ağrı İfadesi Yok / Gülümsüyor'), (1, '1. Nadir Yüz Buruşturma, Çatık Kaş İlgisiz'), (2, '2. Sık Sık Çenesini ve Dişlerini Sıkıyor')], default=0, verbose_name='Davranışsal Ağrı Skalası - Yüz İfadesi (0-2)')),
                ('behavioralLegMovementsPainScale', models.PositiveSmallIntegerField(choices=[(0, '0. Normal / Rahat Pozisyonda'), (1, '1. Huzursuz'), (2, '2. Tekmeleme / Bacakları Çekme')], default=0, verbose_name='Davranışsal Ağrı Skalası - Bacak Hareketleri (0-2)')),
                ('behavioralActivityPainScale', models.PositiveSmallIntegerField(choices=[(0, '0. Sakin Yatış / Rahat Pozisyon'), (1, '1. Gergin / Kıvranıyor'), (2, '2. Hassas / Gergin')], default=0, verbose_name='Davranışsal Ağrı Skalası - Aktivite (0-2)')),
                ('behavioralCryPainScale', models.PositiveSmallIntegerField(choices=[(0, '0. Ağlama Yok'), (1, '1. Arasıra İnleme / Ağlama'), (2, '2. Sürekli Ağlama / Bağırma')], default=0, verbose_name='Davranışsal Ağrı Skalası - Ağlama (0-2)')),
                ('behavioralComfortedPainScale', models.PositiveSmallIntegerField(choices=[(0, '0. Memnun / Rahat'), (1, '1. Arasıra Çevreden Rahatsız'), (2, '2. Avutulması Zor')], default=0, verbose_name='Davranışsal Ağrı Skalası - Avutulma (0-2)')),
                ('bed', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='genotip.bed', verbose_name='Yatak ve Oda Bilgileri')),
                ('service', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='genotip.service', verbose_name='Servis Bilgileri')),
                ('user', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Ağrı Formu',
                'verbose_name_plural': 'Ağrı Formları',
            },
        ),
        migrations.CreateModel(
            name='PainTargetedLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Hedeflenen Ağrı Düzeyi (Hasta İle İşbirliği Halinde Hemşire Tarafından)')),
                ('date', models.DateTimeField(verbose_name='Tarih/Saat')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Düzenleme Tarihi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('pain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.pain', verbose_name='Ağrı Formu')),
            ],
            options={
                'verbose_name': 'Hedeflenen Ağrı Düzeyi (Hasta İle İşbirliği Halinde Hemşire Tarafından)',
                'verbose_name_plural': 'Hedeflenen Ağrı Düzeyi Kayıtları',
            },
        ),
        migrations.CreateModel(
            name='PainSeverity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Ağrının Şiddeti (Skalalardan Uygun Olan Kullanılır)')),
                ('date', models.DateTimeField(verbose_name='Tarih/Saat')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Düzenleme Tarihi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('pain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.pain', verbose_name='Ağrı Formu')),
            ],
            options={
                'verbose_name': 'Ağrının Şiddeti (Skalalardan Uygun Olan Kullanılır)',
                'verbose_name_plural': 'Ağrı Şiddeti Kayıtları',
            },
        ),
        migrations.CreateModel(
            name='PainScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Ağrı Skalası (Numerik Davransal Yüz)')),
                ('date', models.DateTimeField(verbose_name='Tarih/Saat')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Düzenleme Tarihi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('pain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PainScales', to='form.pain', verbose_name='Ağrı Formu')),
            ],
            options={
                'verbose_name': 'Ağrı Skalası (Numerik Davransal Yüz)',
                'verbose_name_plural': 'Ağrı Skala Kayıtları',
            },
        ),
        migrations.CreateModel(
            name='PainPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Ağrının Yeri (Hastanın Kendi İfadesi / Hemşirenin Gözlemi)')),
                ('date', models.DateTimeField(verbose_name='Tarih/Saat')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Düzenleme Tarihi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('pain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.pain', verbose_name='Ağrı Formu')),
            ],
            options={
                'verbose_name': 'Ağrının Yeri (Hastanın Kendi İfadesi / Hemşirenin Gözlemi)',
                'verbose_name_plural': 'Ağrı Yeri Kayıtları',
            },
        ),
        migrations.CreateModel(
            name='PainNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Ağrının Niteliği (Hastanın Kendi İfadesi İle)')),
                ('date', models.DateTimeField(verbose_name='Tarih/Saat')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Düzenleme Tarihi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('pain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.pain', verbose_name='Ağrı Formu')),
            ],
            options={
                'verbose_name': 'Ağrının Niteliği (Hastanın Kendi İfadesi İle)',
                'verbose_name_plural': 'Ağrı Niteliği Kayıtları',
            },
        ),
        migrations.CreateModel(
            name='PainIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pain_severity', models.TextField(blank=True, null=True, verbose_name='Ağrının Şiddeti')),
                ('medicine_detail', models.TextField(blank=True, null=True, verbose_name='Yapılan Uygulama - İlaç Adı, Dozu ve Uygulama Yolu')),
                ('out_of_medicine', models.TextField(blank=True, null=True, verbose_name='Yapılan Uygulama - İlaç Dışı Uygulama')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Not')),
                ('date', models.DateTimeField(verbose_name='Tarih/Saat')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Düzenleme Tarihi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('pain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.pain', verbose_name='Ağrı Formu')),
            ],
            options={
                'verbose_name': 'Yapılan Uygulama',
                'verbose_name_plural': 'Yapılan Uygulama Kayıtları',
            },
        ),
        migrations.CreateModel(
            name='PainFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Ağrının Sıklığı (Hastanın Kendi İfadesi İle)')),
                ('date', models.DateTimeField(verbose_name='Tarih/Saat')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Düzenleme Tarihi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('pain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.pain', verbose_name='Ağrı Formu')),
            ],
            options={
                'verbose_name': 'Ağrının Sıklığı (Hastanın Kendi İfadesi İle)',
                'verbose_name_plural': 'Ağrı Sıklığı Kayıtları',
            },
        ),
        migrations.CreateModel(
            name='PainFactorAffecting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Ağrıyı Etkileyen Faktörler (Hastanın Kendi İfadesi / Hemşirenin Gözlemi)')),
                ('date', models.DateTimeField(verbose_name='Tarih/Saat')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Düzenleme Tarihi')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('pain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.pain', verbose_name='Ağrı Formu')),
            ],
            options={
                'verbose_name': 'Ağrıyı Etkileyen Faktörler (Hastanın Kendi İfadesi / Hemşirenin Gözlemi)',
                'verbose_name_plural': 'Ağrı Faktör Kayıtları',
            },
        ),
    ]
