# Generated by Django 4.2.7 on 2023-12-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observationtracking',
            name='implementation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Uygulama - Tarih/Saat'),
        ),
    ]
