SELECT
    ID,
    KULLANICIADI,
    SIFRE,
    KULLANICI,
    SUPER,
    PASIF,
    GRUP INTO FORMEDICAL.dbo.TABLE_GENOTIP_KULLAN
FROM
    GEN2000.dbo.KULLAN
GO
ALTER TABLE
    FORMEDICAL.dbo.TABLE_GENOTIP_KULLAN
ADD
    PRIMARY KEY (ID);