"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@-h+de%7g$o=1n%z8$x4c)lsk*9^%3!jk3d^b3tjrlacdpi**^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition
INSTALLED_APPS = [
    'baton',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_object_actions',
    # -------------------
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # -------------------
    'django.contrib.humanize',
    'app',
    'genotip',
    'form',
    'baton.autodiscover',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'
AUTH_USER_MODEL = 'genotip.User'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'template'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

""" DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
} """

DATABASES = {
    "default": {
        "ENGINE": "mssql",
        "NAME": "FORMEDICAL",
        "USER": "SA",
        "PASSWORD": "764864",
        "HOST": "ILKADAMNB",
        "PORT": "1433",
        "OPTIONS": {
            "driver": "ODBC Driver 17 for SQL Server",
            # "driver": "FreeTDS",
        },
    },
    # "genotip": {
    #     "ENGINE": "mssql",
    #     "NAME": "GEN2000",
    #     "USER": "SA",
    #     "PASSWORD": "764864",
    #     "HOST": "ILKADAMNB",
    #     "PORT": "1433",
    #     "MIGRATE": False,
    #     "OPTIONS": {
    #         "driver": "ODBC Driver 17 for SQL Server",
    #         # "driver": "FreeTDS",
    #     },
    # },
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'tr-TR'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# DJANGO_ADMIN_LOGS_ENABLED = False

# LOGGING_CONFIG = None

# LOGGING={
#     "version": 1,
#     "disable_existing_loggers": True,
# }

BATON = {
    'SITE_HEADER': 'ForMedical',
    'SITE_TITLE': 'ForMedical Yönetim Paneli',
    'INDEX_TITLE': 'ForMedical - Hemşire Formları Yönetimine, Hoşgeldiniz.',
    'LOGIN_SPLASH': '/static/login-splash.jpg',
    'GRAVATAR_ENABLED': False,
    'SUPPORT_HREF': 'https://www.ilkadam.com.tr',
    'COPYRIGHT': '©2023 İLKADAM YAZILIM VE BİLİŞİM TEKNOLOJİLERİ',
    'POWERED_BY': '<a href="https://ilkadam.com.tr">www.ilkadam.com.tr</a>',
    # 'CHANGELIST_FILTERS_IN_MODAL': True,
    # 'CHANGELIST_FILTERS_ALWAYS_OPEN': False,
    # 'CHANGELIST_FILTERS_FORM': True,
}