# Generated by Django 4.2.6 on 2023-10-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('dosyano', models.CharField(db_column='DOSYANO', max_length=15, unique=True, verbose_name='Dosya Numarası')),
                ('ad', models.CharField(blank=True, db_column='AD', max_length=20, null=True, verbose_name='Adı')),
                ('soyad', models.CharField(blank=True, db_column='SOYAD', max_length=20, null=True, verbose_name='Soyadı')),
                ('dogumtarih', models.DateTimeField(blank=True, db_column='DOGUMTARIH', null=True, verbose_name='Doğum Tarihi')),
                ('cinsiyet', models.CharField(blank=True, db_column='CINSIYET', max_length=5, null=True, verbose_name='Cinsiyeti')),
                ('vatandaslikno', models.CharField(blank=True, db_column='VATANDASLIKNO', max_length=50, null=True, verbose_name='Vatandaşlık Numarası')),
            ],
            options={
                'verbose_name': 'Hasta Kaydı',
                'verbose_name_plural': 'Hasta Kayıtları',
                'db_table': 'VIEW_GENOTIP_KIMLIK',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('dosyano', models.CharField(db_column='DOSYANO', max_length=15, verbose_name='Dosya Numarası')),
                ('gelisno', models.SmallIntegerField(db_column='GELISNO', verbose_name='Geliş No')),
                ('servis', models.CharField(blank=True, db_column='SERVIS', max_length=20, null=True, verbose_name='Servis')),
                ('doktor', models.CharField(blank=True, db_column='DOKTOR', max_length=25, null=True, verbose_name='Doktor')),
                ('oda', models.CharField(blank=True, db_column='ODA', max_length=10, null=True, verbose_name='Oda')),
                ('yatak', models.CharField(blank=True, db_column='YATAK', max_length=5, null=True, verbose_name='Yatak')),
                ('hemsire', models.CharField(blank=True, db_column='HEMSIRE', max_length=25, null=True, verbose_name='Hemşire')),
                ('giristarih', models.DateTimeField(blank=True, db_column='GIRISTARIH', null=True, verbose_name='Giriş Tarihi')),
                ('cikistarih', models.DateTimeField(blank=True, db_column='CIKISTARIH', null=True, verbose_name='Çıkış Tarihi')),
            ],
            options={
                'verbose_name': 'Servis',
                'verbose_name_plural': 'Servisler',
                'db_table': 'VIEW_GENOTIP_SERVIS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('dosyano', models.CharField(db_column='DOSYANO', max_length=15, unique=True, verbose_name='Dosya Numarası')),
                ('gelisno', models.SmallIntegerField(db_column='GELISNO', verbose_name='Geliş No')),
                ('giristarih', models.DateTimeField(blank=True, db_column='GIRISTARIH', null=True, verbose_name='Giriş Tarihi')),
                ('cikistarih', models.DateTimeField(blank=True, db_column='CIKISTARIH', null=True, verbose_name='Çıkış Tarihi')),
                ('yatgunsay', models.SmallIntegerField(blank=True, db_column='YATGUNSAY', null=True, verbose_name='Yattığı Gün Sayısı')),
                ('tedavi', models.CharField(blank=True, db_column='TEDAVI', max_length=15, null=True, verbose_name='Tedavi')),
                ('kurum', models.CharField(blank=True, db_column='KURUM', max_length=200, null=True, verbose_name='Kurum')),
                ('poliklinik', models.CharField(blank=True, db_column='POLIKLINIK', max_length=20, null=True, verbose_name='Poliklinik')),
                ('doktor', models.CharField(blank=True, db_column='DOKTOR', max_length=50, null=True, verbose_name='Doktor')),
                ('protokolno', models.CharField(blank=True, db_column='PROTOKOLNO', max_length=10, null=True, verbose_name='Protokol')),
                ('icdkodu', models.CharField(blank=True, db_column='ICDKODU', max_length=100, null=True, verbose_name='ICD Kodu')),
                ('icdadi', models.CharField(blank=True, db_column='ICDADI', max_length=200, null=True, verbose_name='ICD Adı')),
            ],
            options={
                'verbose_name': 'Geliş',
                'verbose_name_plural': 'Gelişler',
                'db_table': 'VIEW_GENOTIP_GELISLER',
                'managed': False,
            },
        ),
    ]
