# Generated by Django 4.2.6 on 2023-10-13 21:37

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='KULLANICIADI', max_length=50, unique=True, verbose_name='Kullanıcı Adı')),
                ('password', models.CharField(blank=True, db_column='SIFRE', max_length=10, null=True, verbose_name='Şifre')),
                ('user', models.CharField(blank=True, db_column='KULLANICI', max_length=5, null=True, verbose_name='Kullanıcı')),
                ('group', models.CharField(blank=True, db_column='GRUP', max_length=30, null=True, verbose_name='Grup')),
                ('is_inactive', models.BooleanField(blank=True, db_column='PASIF', default=False, null=True, verbose_name='Pasif ?')),
                ('is_superuser', models.BooleanField(db_column='SUPER', default=False)),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
                'db_table': 'VIEW_GENOTIP_KULLAN',
                'managed': False,
            },
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
